name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.nightly }}

    strategy:
      fail-fast: false
      matrix:
        toolchain: [ 'stable', 'beta' ]
        nightly: [false]
        include:
          - toolchain: 'nightly'
            nightly: true

    steps:
    - uses: actions/checkout@v4
    
    - name: Install ${{ matrix.toolchain }} toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
        components: clippy, rustfmt
    
    - uses: Swatinem/rust-cache@v2

    - name: Run cargo fmt
      run: cargo fmt --all --check

    - name: Run tests
      run: cargo test --all-features --all-targets --verbose

    - name: Run doc tests
      run: cargo test --doc --verbose

    - name: Run clippy
      run: cargo clippy --all-targets --all-features
